### ISSUE TITLE
Feature request: Quiet everything

### ISSUE THREAD

**Issue by qualiall** [whiteshark-1975/CitiesSkyline2-CheatOverhaul#2]
Thank you for fixing the Elementary school noise issue.  High school is pretty bad as is Welfare office and a whole bunch of stuff-if there would be an option to just make everything quiet, that would be awesome.  I don't know if the game needs it or not for calculating things.  I think no other kinds of polution in general would be awesome too, but I think maybe the game needs it for proper calculations of land value, recycling, haz-mat handling and such, or I could be completely off base and it doesn't matter.

**Comment by whiteshark-1975** [comment]
*new update today*

*im working on a settings file might be released this week i hope, and next
buildings will be *
*more garbage*

*police firestations *
*thats probably dropping in as 3.16*


*parks and signature building as 3.17*

<https://www.avast.com/sig-email?utm_medium=email&utm_source=link&utm_campaign=sig-email&utm_content=webmail>
Virusvrij.www.avast.com
<https://www.avast.com/sig-email?utm_medium=email&utm_source=link&utm_campaign=sig-email&utm_content=webmail>
<#DAB4FAD8-2DD7-40BB-A1B8-4E2AA1F9FDF2>

Op vr 8 dec 2023 om 18:37 schreef qualiall ***@***.***>:

**Comment by whiteshark-1975** [comment]
has been handled with 0.3.17 all settings are now user managed
