### ISSUE TITLE
Seems to not be working since patch

### ISSUE THREAD

**Issue by qualiall** [whiteshark-1975/CitiesSkyline2-CheatOverhaul#3]
Since the patch I am seeing noise pollution again on buildings that this mod takes care of-  I'm sure you already know but reporting for due diligence anyway.

**Comment by whiteshark-1975** [comment]
are you awre that the mod requires you to delete the old settingsfile and that all values have been set to vanilla since 0.3.17
its gonna be up to the player to set the values to the assets they wish to modify

**Comment by whiteshark-1975** [comment]
i verified it and its still works fine. Verify your settingsfile.
