### ISSUE TITLE
configfile

### ISSUE THREAD

**Issue by Rene123** [whiteshark-1975/CitiesSkyline2-CheatOverhaul#4]
Installing the update, and running the game. I had to manually remove the config file to get a new one, and then edit the old values back in.

**Comment by whiteshark-1975** [comment]
yh if you have a good json editor ist actually easy.
just make sure verify the incinerator section since i added stuff in there recently.
and the look at the bottom of your file what the last addition was.

**Comment by whiteshark-1975** [comment]
https://thunderstore.io/c/cities-skylines-ii/p/Whiteshark/Whiteshark_Cheat_Overhaul/wiki/651-changelog/
i also try to add here what new sections have been added the mod

**Comment by whiteshark-1975** [comment]
and a schema-settings.json is added also so you should be fine entering correct value.
Some are negative values, wich you need keep negative since i do a check on those
some are int so they need to be 1 2 3 4 5 6
some are float /numeric wich can be 0.1, 0.2 and so on
