### ISSUE TITLE
Postoffice

### ISSUE THREAD

**Issue by Rene123** [whiteshark-1975/CitiesSkyline2-CheatOverhaul#5]
"Postoffice_Options": [
  {
    "Name": "PostOffice01",
    "Mailstoragecapacity": 1000000,
    "Mailboxcapacity": 5000,
    "Postvancapacity": 200,
    "PostTruckscapacity": "01000",
    "Upkeep": 0,
    "GarbageAccumulation": 0,
    "Electricityconsumption": 0,
    "Waterconsumption": 0,
    "Range": 20000,
    "Capacity": 150000,
    "Magnitude": 2,
    "Noisepollution": 0
  }
],

This is what I edited the Postoffice to, and perhaps setting the GEW to 1, it might help it, but when placing a new postoffice and adding the upgrades, the building starts to ask for GEW.

GEW (Garbage, Electricity, Water)

**Comment by whiteshark-1975** [comment]
wich is normal, the extention building are on my desk for this weekend
there are no extention buildings in the mod yet.
So all basicbuildings are done except public transport wich i will try todo tommorow
next on the agenda will be all the extention buildings

**Comment by whiteshark-1975** [comment]
if you check the source youll see its alot of work to add stuff, i try todo as much i can and i post every 2 days an update.
also if you intrested there is an hotfix available on the sourcepage.
For bank and city hall wich both had a loanintrest bug.
dont delete your settings to use the hotfix just swap the mod
